### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yuki-MIRA** [yuki-MIRA/furima-30334#10]
# URL
https://furima-30334.herokuapp.com/
# Basic認証のIDとパスワード
ID：yukiyu
パスワード： 1479
# 出品者用のメールアドレスとパスワード
アドレス：yuki@com
パスワード：y11111
# 購入者用のメールアドレスとパスワード
アドレス：ame@com
パスワード：y11111
# 購入用カードの番号・期限・セキュリティコード
カード番号：4242424242424242
期限：月→12、年→21
セキュリティコード：123

**Comment by chika15** [comment]
尾下さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下2点の不備が見受けられましたので修正をお願いします！

=====
[修正箇所]

**商品出品機能**
⦿確認項目：
ログイン状態のユーザーだけが、商品出品ページへ遷移できること
ログアウト状態のユーザーは、商品出品ページへ遷移しようとすると、ログインページへ遷移すること

〈修正依頼〉
現在ログアウト状態でも商品出品ページに遷移されますので、ログインページへ遷移するよう修正をお願いします。

**商品編集機能**
⦿確認項目：
ログイン状態の出品者以外のユーザーは、URLを直接入力して出品していない商品の商品情報編集ページへ遷移しようとすると、トップページに遷移すること

〈修正依頼〉
ログイン状態の出品者以外のユーザーでも商品情報編集ページへ遷移されますので、トップページに遷移するよう修正をお願いします。

======



修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by yuki-MIRA** [comment]
ご確認いただき、ありがとうございます！
上記2点の実装漏れ、失礼致しました。

修正完了しましたので、
お手数ですが、再度ご確認の程よろしくお願い致します。

**Comment by div-shibata** [comment]
尾下さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by yuki-MIRA** [comment]
ご確認ありがとうございました！
引き続き、よろしくお願いします！！
